### DISCUSSION TITLE
Choosing the stack

### DISCUSSION THREAD

**Discussion by wordpad25** [mpiorowski/go-svelte-grpc#17] [Q&A]
Blog post here answers a lot of questions:
https://dev.to/mpiorowski/breaking-the-myth-scalable-multi-region-low-latency-app-exists-and-will-not-cost-you-a-kidney-537a

**Comment by cmjoseph07** [comment]
@mpiorowski 

Can I ask what your IDE setup looks like? Currently I just attach to the container through vscode but have to bring up a wsl instance initially. What would you suggest?

**Reply by mpiorowski** [reply]
I am using neovim :) And just run docker in another terminal. Do you have problem running this stack on wsl?

**Reply by cmjoseph07** [reply]
It's not really a problem, just have to attach to container is vscode as local code not have a node module folder. Thus if I try to develop locally in wsl I get a ton of node error unable to find deps if that makes sense.

On windows with wsl I have to run docker desktop and then attach to them that way.

**Reply by mpiorowski** [reply]
Hmmm, strange one. It shouldn't be a problem, cos I've removed the `node_modules` from volumes in docker-compose, so its build and used only inside linux container :/ But the WSL part is a little bit tricky for me, don't know it well.

If this is still a problem, can you open a separate discussion? Maybe i can help somehow.

For reference:
```
services:
  client:
    container_name: sgsg-client
    build:
      context: ./client
      target: dev
    volumes:
      - ./client/src:/client/src
      - ./client/.svelte-kit:/client/.svelte-kit
    ```
